### ISSUE TITLE
About Chai

### ISSUE THREAD

**Issue by freak4pc** [nelsonic/learn-mocha#19]
I saw that early on , this tutorial had Chai as a dependency ,
Any reason this was removed? I'm wondering if there's anything wrong with it as I'm just getting into TDD and want to do it correctly ;) 

Thanks.

**Comment by nelsonic** [comment]
Great question @freak4pc !
Chai is *not* required to write tests with Mocha.
its 100% optional. and to reduce the number of new things to learn for new people, I removed it.
let us know if you decide to use it in your tests.

Also... we are going to update this repo with a complete re-write. select watch above to receive the update. :+1:

**Comment by freak4pc** [comment]
Thanks @nelsonic  , 
Any idea when the rewrite is happening? :) 
Wondering is i should hold on my learning for a bit ...

**Comment by nelsonic** [comment]
The re-write is happening *right now*. but you can go ahead and learn mocha in the mean time.

**Comment by freak4pc** [comment]
Alright I hope there's not too much deprecated info in here :)
Many thanks Nelson!
